compile: &defaults
  build: .
  volumes:
    - .:/home/mruby/code:rw
  command: rake compile
test:
  <<: *defaults
  command: rake test
bintest:
  <<: *defaults
  command: rake test:bintest
mtest:
  <<: *defaults
  command: rake test:mtest
clean:
  <<: *defaults
  command: rake clean
shell:
  <<: *defaults
  command: bash

app:
  build: ./builds
  volumes:
    - ./builds:/app
  environment:
    - BLACKSTAR_ENV=dev
  ports:
    - "13337:13337"
